#!/usr/bin/env bash

php artisan make:controller --api API\\V1\\AssetController
php artisan make:controller --api API\\V1\\BillingInfoController
php artisan make:controller --api API\\V1\\CartController
php artisan make:controller --api API\\V1\\CompanyController
php artisan make:controller --api API\\V1\\CouponController
php artisan make:controller --api API\\V1\\DomainController
php artisan make:controller --api API\\V1\\InvoiceItemController
php artisan make:controller --api API\\V1\\InvoiceController
php artisan make:controller --api API\\V1\\NotificationController
php artisan make:controller --api API\\V1\\PermissionController
php artisan make:controller --api API\\V1\\ProductController
php artisan make:controller --api API\\V1\\RegistrarController
php artisan make:controller --api API\\V1\\ResellerController
php artisan make:controller --api API\\V1\\RoleController
php artisan make:controller --api API\\V1\\ServiceController
php artisan make:controller --api API\\V1\\SubscriptionController
php artisan make:controller --api API\\V1\\NameserverCommentController
php artisan make:controller --api API\\V1\\NameserverCryptokeyController
php artisan make:controller --api API\\V1\\NameserverDomainmetadataController
php artisan make:controller --api API\\V1\\NameserverDomainController
php artisan make:controller --api API\\V1\\NameserverRecordController
php artisan make:controller --api API\\V1\\NameserverSupermasterController
php artisan make:controller --api API\\V1\\NameserverTsigkeyController
php artisan make:controller --api API\\V1\\RoleController
php artisan make:controller --api API\\V1\\EmployeeController
php artisan make:controller --api API\\V1\\VendorController
php artisan make:controller --api API\\V1\\WhitegloveController
php artisan make:controller --api API\\V1\\ChassisController
php artisan make:controller --api API\\V1\\CommentController
php artisan make:controller --api API\\V1\\ControlPanelController
php artisan make:controller --api API\\V1\\CpuController
php artisan make:controller --api API\\V1\\DatacenterController
php artisan make:controller --api API\\V1\\DepartmentController
php artisan make:controller --api API\\V1\\DiskController
php artisan make:controller --api API\\V1\\FirewallZoneController
php artisan make:controller --api API\\V1\\IpAddressController
php artisan make:controller --api API\\V1\\MemoryController
php artisan make:controller --api API\\V1\\MotherboardTypeController
php artisan make:controller --api API\\V1\\NetworkConfigurationController
php artisan make:controller --api API\\V1\\NetworkDeviceController
php artisan make:controller --api API\\V1\\NetworkDeviceTypeController
php artisan make:controller --api API\\V1\\NetworkInterfaceCardController
php artisan make:controller --api API\\V1\\NoteController
php artisan make:controller --api API\\V1\\OperatingSystemController
php artisan make:controller --api API\\V1\\QueueController
php artisan make:controller --api API\\V1\\SalesRepController
php artisan make:controller --api API\\V1\\StatusController
php artisan make:controller --api API\\V1\\SubnetAddressController
php artisan make:controller --api API\\V1\\SwitchportInformationController
php artisan make:controller --api API\\V1\\TechnicianController
php artisan make:controller --api API\\V1\\TicketController
php artisan make:controller --api API\\V1\\TldExtensionController
php artisan make:controller --api API\\V1\\AboutUsController
php artisan make:controller --api API\\V1\\MenuPageController
